### ISSUE TITLE
請問書中p.43，程式碼打完改完，請問要如何開啟抓取資料，因為書中沒有這部份。謝謝。

### ISSUE THREAD

**Issue by abedul59** [chunkai1312/nodejs-investing-twstock#1]

**Comment by abedul59** [comment]
請問書中p.43，程式碼打完改完，請問要如何開啟抓取資料，因為書中沒有這部份。謝謝。
只有說「透過呼叫此方法，即可取得上市或上櫃股票清單」。

**Comment by chunkai1312** [comment]
Hi @abedul59, 

謝謝提問。如果您想立即測試執行結果的話，可以在該 `TwseScraperService` 加入 `onApplicationBootstrap()` 這個 lifecyle hook，例如：

```ts
@Injectable()
export class TwseScraperService {
  constructor(private httpService: HttpService) {}

  async onApplicationBootstrap() {
    const tse = await this.fetchListedStocks({ market: 'TSE' });
    console.log(tse);   // 顯示上市公司股票清單

    const otc = await this.fetchListedStocks({ market: 'OTC' });
    console.log(otc);   // 顯示上櫃公司股票清單
  }

  ...
}
```

然後打開終端機輸入以下指令執行應用程式：

```sh
$ npm start
```

就可以查看資料抓取的結果了。


> Nest 提供 [Lifecycle Events](https://docs.nestjs.com/fundamentals/lifecycle-events) 機制，onApplicationBootstrap() 會在所有 modules 都被初始化後執行。注意這裡加入 onApplicationBootstrap() 方法只是方便查看執行結果，確認程式執行無誤後記得移除該方法，否則每次執行應用程式前都會先執行 onApplicationBootstrap() 內的程式碼。

**Comment by abedul59** [comment]
感謝您很快回答，等等試試看。

**Comment by abedul59** [comment]
確定可行，感恩！
