### ISSUE TITLE
想再請問一個問題。

### ISSUE THREAD

**Issue by abedul59** [chunkai1312/nodejs-investing-twstock#2]
為何這本書不用單純node.js的爬蟲機制來抓資料，而是使用nest.js？我有Python爬蟲的背景，有個網站用Django製作，背後用Python抓資料到資料庫裡呈現。感謝。

**Comment by chunkai1312** [comment]
Hi @abedul59 , 
使用單純 Node.js 的爬蟲機制來抓資料當然也可以！不過這本書的目標是建立一套比較完整的個人化投資系統，之所以選擇使用 NestJS，是因為它已經整合了大部分後端功能，包括任務排程等，有助於我們建立易於維護的應用程式。
PART 2 章節的內容主要是說明如何取得市場資料來源幫助投資分析，在後續 PART 3 的章節裡就會說明如何搭配資料庫，做實際的應用來打造個人化的投資工具！謝謝提問。

**Comment by abedul59** [comment]
感謝回答。
